/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.EOFException;
import java.io.File;
import java.io.InputStream;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.border.LineBorder;
import javax.swing.text.html.parser.Entity;

import dao.ConnetServerDAO;
import dao.UserDAO;
import helper.Auth;
import helper.Handle;
import helper.MsgBox;
import helper.XImage;
import entity.User;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;


/**
 *
 * @author thaip
 */
public class UserJDialog extends javax.swing.JDialog {
    
    ConnetServerDAO iforDao = new ConnetServerDAO();
    /**
     * Creates new form NewJDialog
     */
    public UserJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init();
        this.pnlBoxRegister.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBoxLogin = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        pnlRegister = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        lblErroLogin = new javax.swing.JLabel();
        cboServer = new javax.swing.JComboBox<>();
        pnlBoxRegister = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnDangKi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        txtEmail1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblErroPass2 = new javax.swing.JLabel();
        lblErroUserName = new javax.swing.JLabel();
        lblBgRegister = new javax.swing.JLabel();
        lblBgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBoxLogin.setBackground(new java.awt.Color(102, 102, 102));
        pnlBoxLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Tài khoản");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        pnlBoxLogin.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 113, 210, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP");
        pnlBoxLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 270, -1));

        txtPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("123123123");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        pnlBoxLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 153, 210, 24));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/person-icon.png"))); // NOI18N
        pnlBoxLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 113, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock-icon.png"))); // NOI18N
        pnlBoxLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 153, -1, -1));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        pnlBoxLogin.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 11, 20, -1));

        lblUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlBoxLogin.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 30));

        lblPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlBoxLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 250, 30));

        pnlLogin.setBackground(new java.awt.Color(0, 153, 153));

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("ĐĂNG NHẬP");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlBoxLogin.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 40));

        jCheckBox1.setBackground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Ghi nhớ tài khoản");
        pnlBoxLogin.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quên mật khẩu ?");
        pnlBoxLogin.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, 20));

        pnlRegister.setBackground(new java.awt.Color(102, 102, 102));

        lblRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setText("ĐĂNG KÝ");
        lblRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegisterMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlBoxLogin.add(pnlRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 250, 30));

        lblErroLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblErroLogin.setForeground(new java.awt.Color(255, 102, 102));
        pnlBoxLogin.add(lblErroLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, 250, 20));

        cboServer.setBackground(new java.awt.Color(102, 102, 102));
        cboServer.setForeground(new java.awt.Color(255, 255, 255));
        cboServer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Localhost", "Server" }));
        pnlBoxLogin.add(cboServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 330, 100, 20));

        jPanel1.add(pnlBoxLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 270, 370));

        pnlBoxRegister.setLayout(null);

        btnThoat.setBackground(new java.awt.Color(102, 102, 102));
        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Huỷ");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pnlBoxRegister.add(btnThoat);
        btnThoat.setBounds(20, 315, 110, 30);

        txtPassword1.setBackground(new java.awt.Color(0, 153, 204));
        txtPassword1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword1.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassword1MouseClicked(evt);
            }
        });
        pnlBoxRegister.add(txtPassword1);
        txtPassword1.setBounds(20, 200, 230, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Xác nhận mật khẩu");
        pnlBoxRegister.add(jLabel5);
        jLabel5.setBounds(20, 240, 140, 20);

        btnDangKi.setBackground(new java.awt.Color(0, 153, 153));
        btnDangKi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangKi.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKi.setText("Đăng kí");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });
        pnlBoxRegister.add(btnDangKi);
        btnDangKi.setBounds(140, 315, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên đăng nhập");
        pnlBoxRegister.add(jLabel6);
        jLabel6.setBounds(20, 60, 110, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mật khẩu");
        pnlBoxRegister.add(jLabel7);
        jLabel7.setBounds(20, 180, 230, 20);

        txtPassword2.setBackground(new java.awt.Color(0, 153, 204));
        txtPassword2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword2.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassword2MouseClicked(evt);
            }
        });
        pnlBoxRegister.add(txtPassword2);
        txtPassword2.setBounds(20, 260, 230, 25);

        txtEmail1.setBackground(new java.awt.Color(0, 153, 204));
        txtEmail1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail1.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEmail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmail1MouseClicked(evt);
            }
        });
        pnlBoxRegister.add(txtEmail1);
        txtEmail1.setBounds(20, 140, 230, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        pnlBoxRegister.add(jLabel9);
        jLabel9.setBounds(20, 120, 230, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đăng Ký");
        pnlBoxRegister.add(jLabel1);
        jLabel1.setBounds(20, 10, 101, 29);

        txtUserName.setBackground(new java.awt.Color(0, 153, 204));
        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });
        pnlBoxRegister.add(txtUserName);
        txtUserName.setBounds(20, 80, 230, 25);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        pnlBoxRegister.add(jPanel2);
        jPanel2.setBounds(20, 105, 230, 2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        pnlBoxRegister.add(jPanel3);
        jPanel3.setBounds(20, 165, 230, 2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        pnlBoxRegister.add(jPanel4);
        jPanel4.setBounds(20, 225, 230, 2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        pnlBoxRegister.add(jPanel5);
        jPanel5.setBounds(20, 285, 230, 2);

        lblErroPass2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErroPass2.setForeground(new java.awt.Color(255, 0, 51));
        lblErroPass2.setText("e");
        pnlBoxRegister.add(lblErroPass2);
        lblErroPass2.setBounds(160, 240, 90, 20);

        lblErroUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblErroUserName.setForeground(new java.awt.Color(255, 0, 0));
        lblErroUserName.setText("w");
        pnlBoxRegister.add(lblErroUserName);
        lblErroUserName.setBounds(130, 60, 120, 20);

        lblBgRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue.jpg"))); // NOI18N
        pnlBoxRegister.add(lblBgRegister);
        lblBgRegister.setBounds(0, 0, 270, 370);

        jPanel1.add(pnlBoxRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 270, 370));

        lblBgLogin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblBgLoginAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(lblBgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 240, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.pnlBoxRegister.setVisible(false);
        this.pnlBoxLogin.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        this.isRegistre();
    }//GEN-LAST:event_btnDangKiActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtPassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword1MouseClicked
        // TODO add your handling code here:
        txtPassword1.setText(null);
        txtPassword1.setBorder(new LineBorder(Color.white,1));
    }//GEN-LAST:event_txtPassword1MouseClicked

    private void txtPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword2MouseClicked
        // TODO add your handling code here:
        txtPassword2.setText(null);
        lblErroPass2.setText(null);
        txtPassword2.setBorder(new LineBorder(Color.white,1));
    }//GEN-LAST:event_txtPassword2MouseClicked

    private void lblBgLoginAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblBgLoginAncestorAdded
        try {
            BufferedImage image = ImageIO.read(new File("src/img/003.jpg"));
            lblBgLogin.setIcon(new ImageIcon(image.getScaledInstance(lblBgLogin.getWidth(), lblBgLogin.getHeight(), Image.SCALE_SMOOTH)));
        } catch (Exception ex) {}
    }//GEN-LAST:event_lblBgLoginAncestorAdded

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
        txtEmail.setText(null);
        lblUserName.setBorder(new LineBorder(Color.white,1));
        lblErroLogin.setText(null);
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        txtPassword.setText(null);
        lblPassword.setBorder(new LineBorder(Color.white,1));
        lblErroLogin.setText(null);
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        this.isLogin();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        // TODO add your handling code here:
        this.pnlBoxLogin.setVisible(false);
        this.pnlBoxRegister.setVisible(true);
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        // TODO add your handling code here:
        pnlLogin.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        // TODO add your handling code here:
        pnlLogin.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_lblLoginMouseExited

    private void lblRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseEntered
        // TODO add your handling code here:
        pnlRegister.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_lblRegisterMouseEntered

    private void lblRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseExited
        // TODO add your handling code here:
        pnlRegister.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblRegisterMouseExited

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        // TODO add your handling code here:
        txtUserName.setText(null);
        txtUserName.setBorder(new LineBorder(Color.white,1));
        lblErroUserName.setText(null);
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtEmail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmail1MouseClicked
        // TODO add your handling code here:
        txtEmail1.setText(null);
        txtEmail1.setBorder(new LineBorder(Color.white,1));
        //lblErroUserName.setText(null);
    }//GEN-LAST:event_txtEmail1MouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        lblClose.setForeground(Color.red);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                UserJDialog dialog = new UserJDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboServer;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblBgLogin;
    private javax.swing.JLabel lblBgRegister;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblErroLogin;
    private javax.swing.JLabel lblErroPass2;
    private javax.swing.JLabel lblErroUserName;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlBoxLogin;
    private javax.swing.JPanel pnlBoxRegister;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private ConnetServerDAO csdao = new ConnetServerDAO();
    private UserDAO usdao = new UserDAO();
    private String inetAddress = "localhost";
    private void init(){
        this.setTitle("LOGIN");
        this.setLocationRelativeTo(null); 
        this.setIconImage(XImage.getApplcon());
        lblErroUserName.setText(null);
        lblErroPass2.setText(null);
    }
    User getFormLogin(){
        User user = new User();
        user.setUserName(txtEmail.getText());
        user.setPass(txtPassword.getText());
        return user;
    }
    void isLogin(){ 
        User user = getFormLogin();
        try {
            Handle.checkNull(txtEmail, txtPassword);
            //csdao.server(cboServer.getSelectedIndex());
            csdao.connetServer();
            if (csdao.checkConnet()){
                csdao.outputClinet(usdao.outputUser(user));
                String[] data = csdao.inputClient().split("\\s");
                if (data[0].equals("true")){
                    user.setId(Integer.parseInt(data[1]));
                    Auth.user = user;
                    this.dispose();
                }else{
                    lblPassword.setBorder(new LineBorder(new Color(255,102,102)));
                    lblUserName.setBorder(new LineBorder(new Color(255,102,102)));
                    lblErroLogin.setText("Tài Khoản or Mật Khẩu không đúng!");
                }
            }
        } catch (Exception e) {
            lblErroLogin.setText(e.getMessage());
        }
    }
    User getFormRegistre(){
        User user = new User();
        user.setUserName(txtUserName.getText());
        user.setEmail(txtEmail1.getText());
        user.setPass(txtPassword1.getText());
        return user;
    }
    void isRegistre(){
        User user = getFormRegistre();
        try {
            Handle.checkNullRegister(txtUserName, txtEmail1, txtPassword1, txtPassword2);
            //csdao.server(cboServer.getSelectedIndex());
            if (!Handle.checkPass(txtPassword1, txtPassword2)){
                lblErroPass2.setText("không giống nhau!");
                txtPassword2.setBorder(new LineBorder(Color.red,1));
            }else{
                csdao.connetServer();
                if (csdao.checkConnet()){
                    csdao.outputClinet(usdao.outputRegister(user));
                    String str = csdao.inputClient();
                    if(str.equals("warring")){
                        lblErroUserName.setText("đã tồn tại!");
                        txtUserName.setBorder(new LineBorder(Color.red,1));
                    }else{
                        user.setId(Integer.parseInt(str));
                        MsgBox.alert(this, "Đăng ký thành công rồi!", 1);
                        Auth.user = user;
                        this.dispose();
                    }
                }
            }
        } catch (Exception e) {}
    }
}
